export const options = [
{value: 'Administrative law' ,label: 'Administrative law'},
{value: 'Advertising law' ,label: 'Advertising law'},
{value: 'Admiralty law' ,label: 'Admiralty law'},
{value: 'Agency law' ,label: 'Agency law'},
{value: 'Alcohol law' ,label: 'Alcohol law'},
{value: 'Alternative dispute resolution' ,label: 'Alternative dispute resolution'},
{value: 'Animal law' ,label: 'Animal law'},
{value: 'Antitrust law (or competition law)' ,label: 'Antitrust law (or competition law)'},
{value: 'Appellate practice' ,label: 'Appellate practice'},
{value: 'Art law (or art and culture law)' ,label: 'Art law (or art and culture law)'},
{value: 'Aviation law' ,label: 'Aviation law'},
{value: 'Banking law' ,label: 'Banking law'},
{value: 'Bankruptcy law (creditor debtor rights law or insolvency and reorganization law)' ,label: 'Bankruptcy law (creditor debtor rights law or insolvency and reorganization law)'},
{value: 'Bioethics' ,label: 'Bioethics'},
{value: 'Business law (or commercial law); commercial litigation' ,label: 'Business law (or commercial law); commercial litigation'},
{value: 'Business organizations law (or companies law)' ,label: 'Business organizations law (or companies law)'},
{value: 'Civil law or common law' ,label: 'Civil law or common law'},
{value: 'Class action litigation/Mass tort litigation' ,label: 'Class action litigation/Mass tort litigation'},
{value: 'Common Interest Development law' ,label: 'Common Interest Development law'},
{value: 'Communications law' ,label: 'Communications law'},
{value: 'Computer law' ,label: 'Computer law'},
{value: 'Competition law' ,label: 'Competition law'},
{value: 'Conflict of law (or private international law)' ,label: 'Conflict of law (or private international law)'},
{value: 'Constitutional law' ,label: 'Constitutional law'},
{value: 'Construction law' ,label: 'Construction law'},
{value: 'Consumer law' ,label: 'Consumer law'},
{value: 'Contract law' ,label: 'Contract law'},
{value: 'Copyright law' ,label: 'Copyright law'},
{value: 'Corporate law (or company law), also corporate compliance law and corporate governance law' ,label: 'Corporate law (or company law), also corporate compliance law and corporate governance law'},
{value: 'Criminal law' ,label: 'Criminal law'},
{value: 'Cryptography law' ,label: 'Cryptography law'},
{value: 'Cultural property law' ,label: 'Cultural property law'},
{value: 'Custom (law)' ,label: 'Custom (law)'},
{value: 'Cyber law' ,label: 'Cyber law'},
{value: 'Defamation' ,label: 'Defamation'},
{value: 'Derivatives and futures law' ,label: 'Derivatives and futures law'},
{value: 'Drug control law' ,label: 'Drug control law'},
{value: 'Ecclesiastical law (or Canon law)' ,label: 'Ecclesiastical law (or Canon law)'},
{value: 'Elder law' ,label: 'Elder law'},
{value: 'Employee benefits law (ERISA)' ,label: 'Employee benefits law (ERISA)'},
{value: 'Employment law' ,label: 'Employment law'},
{value: 'Energy law' ,label: 'Energy law'},
{value: 'Entertainment law' ,label: 'Entertainment law'},
{value: 'Environmental law' ,label: 'Environmental law'},
{value: 'Equipment finance law' ,label: 'Equipment finance law'},
{value: 'Family law' ,label: 'Family law'},
{value: 'FDA law' ,label: 'FDA law'},
{value: 'Financial services regulation law' ,label: 'Financial services regulation law'},
{value: 'Firearm law' ,label: 'Firearm law'},
{value: 'Food law' ,label: 'Food law'},
{value: 'Franchise law' ,label: 'Franchise law'},
{value: 'Gaming law' ,label: 'Gaming law'},
{value: 'Health and safety law' ,label: 'Health and safety law'},
{value: 'Health law' ,label: 'Health law'},
{value: 'HOA law' ,label: 'HOA law'},
{value: 'Immigration law' ,label: 'Immigration law'},
{value: 'Insurance law' ,label: 'Insurance law'},
{value: 'Intellectual property law' ,label: 'Intellectual property law'},
{value: 'International law' ,label: 'International law'},
{value: 'International human rights law' ,label: 'International human rights law'},
{value: 'International trade and finance law' ,label: 'International trade and finance law'},
{value: 'Internet law' ,label: 'Internet law'},
{value: 'Juvenile law' ,label: 'Juvenile law'},
{value: 'Labour law (or Labor law)' ,label: 'Labour law (or Labor law)'},
{value: 'Land use & zoning law' ,label: 'Land use & zoning law'},
{value: 'Litigation' ,label: 'Litigation'},
{value: 'Martial law' ,label: 'Martial law'},
{value: 'Media law' ,label: 'Media law'},
{value: 'Medical law' ,label: 'Medical law'},
{value: 'Mergers & acquisitions law' ,label: 'Mergers & acquisitions law'},
{value: 'Military law' ,label: 'Military law'},
{value: 'Mining law' ,label: 'Mining law'},
{value: 'Music law' ,label: 'Music law'},
{value: 'Mutual funds law' ,label: 'Mutual funds law'},
{value: 'Nationality law' ,label: 'Nationality law'},
{value: 'Native American law' ,label: 'Native American law'},
{value: 'Obscenity law' ,label: 'Obscenity law'},
{value: 'Oil & gas law' ,label: 'Oil & gas law'},
{value: 'Parliamentary law' ,label: 'Parliamentary law'},
{value: 'Patent law' ,label: 'Patent law'},
{value: 'Poverty law' ,label: 'Poverty law'},
{value: 'Privacy law' ,label: 'Privacy law'},
{value: 'Private equity law' ,label: 'Private equity law'},
{value: 'Private funds law / Hedge funds law' ,label: 'Private funds law / Hedge funds law'},
{value: 'Procedural law' ,label: 'Procedural law'},
{value: 'Product liability litigation' ,label: 'Product liability litigation'},
{value: 'Property law' ,label: 'Property law'},
{value: 'Public health law' ,label: 'Public health law'},
{value: 'Public International Law' ,label: 'Public International Law'},
{value: 'Railway law' ,label: 'Railway law'},
{value: 'Real estate law' ,label: 'Real estate law'},
{value: 'Securities law / Capital markets law' ,label: 'Securities law / Capital markets law'},
{value: 'Social Security disability law' ,label: 'Social Security disability law'},
{value: 'Space law' ,label: 'Space law'},
{value: 'Sports law' ,label: 'Sports law'},
{value: 'Statutory law' ,label: 'Statutory law'},
{value: 'Tax law' ,label: 'Tax law'},
{value: 'Technology law' ,label: 'Technology law'},
{value: 'Timber law' ,label: 'Timber law'},
{value: 'Tort law' ,label: 'Tort law'},
{value: 'Trademark law' ,label: 'Trademark law'},
{value: 'Transport law / Transportation law' ,label: 'Transport law / Transportation law'},
{value: 'Trusts & estates law' ,label: 'Trusts & estates law'},
{value: 'Utilities Regulation' ,label: 'Utilities Regulation'},
{value: 'Venture capital law' ,label: 'Venture capital law'},
{value: 'Water law',label: 'Venture capital law'}
]
