
module.exports = Object.freeze({

	USER_REGISTER_SUBJECT:"",
	USER_REGISTER_MESSAGE:"",
	
	NEW_APPEARING_USER_SUBJECT:"",
	NEW_APPEARING_USER_MESSAGE:"",
	NEW_RECORD_USER_SUBJECT:"",
	NEW_RECORD_USER_MESSAGE:"",

	USER_RECOVER_PASSWORD_SUBJECT:"",
	USER_RECOVER_PASSWORD_MESSAGE:"",

	APPEARANCE_DELETE_APPEARING_SUBJECT:"",
	APPEARANCE_DELETE_APPEARING_MESSAGE:"",
	APPEARANCE_DELETE_RECORD_SUBJECT:"",
	APPEARANCE_DELETE_RECORD_MESSAGE:"",

	APPEARANCE_UNSUBSCRIBE_APPEARING_SUBJECT:"",
	APPEARANCE_UNSUBSCRIBE_APPEARING_MESSAGE:"",
	APPEARANCE_UNSUBSCRIBE_RECORD_SUBJECT:"",
	APPEARANCE_UNSUBSCRIBE_RECORD_MESSAGE:"",

	APPEARANCE_SUBSCRIBE_APPEARING_SUBJECT:"",
	APPEARANCE_SUBSCRIBE_APPEARING_MESSAGE:"",
	APPEARANCE_SUBSCRIBE_RECORD_SUBJECT:"",
	APPEARANCE_SUBSCRIBE_RECORD_MESSAGE:"",

	APPEARANCE_ACCEPT_APPEARING_SUBJECT:"",
	APPEARANCE_ACCEPT_APPEARING_MESSAGE:"",
	APPEARANCE_ACCEPT_RECORD_SUBJECT:"",
	APPEARANCE_ACCEPT_RECORD_MESSAGE:"",

	APPEARANCE_REJECT_APPEARING_SUBJECT:"",
	APPEARANCE_REJECT_APPEARING_MESSAGE:"",
	APPEARANCE_REJECT_RECORD_SUBJECT:"",
	APPEARANCE_REJECT_RECORD_MESSAGE:"",

    APPEARANCE_COMPLETED_RECORD_SUBJECT:"",
	APPEARANCE_COMPLETED_RECORD_MESSAGE:"",	

	APPEARANCE_FINISHED_APPEARING_SUBJECT:"",
	APPEARANCE_FINISHED_APPEARING_MESSAGE:"",
	APPEARANCE_FINISHED_RECORD_SUBJECT:"",
	APPEARANCE_FINISHED_RECORD_MESSAGE:"",

	APPEARING_RATED_SUBJECT:"",
	APPEARING_RATED_MESSAGE:"",
	RECORD_RATED_SUBJECT:"",
	RECORD_RATED_MESSAGE:"",

	APPEARANCE_STACKING_SUBJECT:"",
	APPEARANCE_STACKING_MESSAGE:"",
	
	REMINDER_UPLOAD_VERDICT_SUBJECT:"",
	REMINDER_UPLOAD_VERDICT_MESSAGE:"",
	
	REMINDER_UPLOAD_RATE_SUBJECT:"",
	REMINDER_UPLOAD_RATE_MESSAGE:"",

	CREATE_APPEARANCE_SUBJECT:"",
	CREATE_APPEARANCE_MESSAGE:"",
	
	NOTIFY_APPEARING_SUBJECT:"NOTIFY_APPEARING_SUBJECT",
	NOTIFY_APPEARING_MESSAGE:"NOTIFY_APPEARING_MESSAGE"
	


})